# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            OS_NAME: Windows
          - os: ubuntu-latest
            OS_NAME: Linux
          - os: macos-latest
            OS_NAME: macOS

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pyinstaller
        pip install -r requirements.txt
    - name: Run build script
      run: |
        python build.py build
    - uses: actions/upload-artifact@v2
      with:
        name: Wiimmfi-RPC_${{ matrix.OS_NAME }}-64bit
        path: Wiimmfi-RPC_*-64bit.zip
